repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0  # Use the ref you want to point at
    hooks:
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-xml
      - id: check-yaml
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v13.0.0
    hooks:
      - id: clang-format  # ClangFormat is a tool to format C/C++/Java/JavaScript/Objective-C/Protobuf code
  #- repo: https://github.com/pocc/pre-commit-hooks
  #  rev: v1.3.5
  #  hooks:
      #- id: cppcheck  # Static analysis tool for C/C++ code
      #- id: cpplint  # Checks C++ code against Google's style guide
