name: Qt CI  # The name of your GitHub Actions workflow.

on:  # Specifies the events that trigger the workflow.
  push:  # The workflow will run when you push to any branch.
  pull_request:  # The workflow will also run when a pull request is made to any branch.
  workflow_dispatch:  # Allows the workflow to be manually triggered from GitHub's web interface.

jobs:  # The collection of jobs that are run in the workflow.
  build:  # The name of the job.
    runs-on: ubuntu-latest  # The type of machine to run the job on. Here it's the latest version of Ubuntu.

    steps:  # The sequence of tasks that make up a job.
    - uses: actions/checkout@v2  # Uses a prebuilt GitHub Action to check out your repository.

    - name: Install Qt  # The name of the step.
      uses: jurplel/install-qt-action@v2  # Uses a prebuilt GitHub Action to install Qt.
      with:  # The parameters to pass to the action.
        version: '6.2.1'  # The version of Qt to install.

    - name: Configure  # The name of the step.
      run: qmake  # Runs qmake to generate a Makefile.

    - name: Build  # The name of the step.
      run: make  # Runs make to build the project.

    - name: Test  # The name of the step.
      run: make check  # Runs the tests of the project. Replace with your test command if different.
